ko9612/Hobbyt

client/.eslintrc.js, client/pages/index.tsx, client/postcss.config.js, client/src/components/Button/example.tsx, client/src/components/Footer/example.tsx, client/src/components/Modal/example.tsx, client/src/components/Nav/example.tsx, client/src/components/ToastUI/example.tsx, client/src/components/UserHome/example.tsx, client/src/image/example.tsx, client/tailwind.config.js
=> setting: ESLint세팅 #3

client/pages/blog.tsx, client/src/components/Tab/BlogList.tsx, client/src/components/Tab/BlogTab.tsx, client/src/components/ViewLikeWrite/LikeCount.tsx, client/src/components/ViewLikeWrite/TodayCount.tsx, client/src/components/ViewLikeWrite/ViewCount.tsx, client/src/components/ViewLikeWrite/WriteDate.tsx, client/styles/globals.css, client/tailwind.config.js
=> style: 개인홈 목업#7

server/src/main/java/com/hobbyt/global/entity/Article.java, server/src/main/java/com/hobbyt/global/entity/BaseEntity.java
=> Feat/seongho/abstraction #11

client/src/components/Tab/BlogTab.tsx, client/src/components/Tab/LikeList.tsx, client/src/components/Tab/MyCommentList.tsx
=> style: 댓글,좋아요 목업#7

client/package-lock.json, client/package.json, client/pages/blogwrite.tsx, client/src/components/ToastUI/TextEditor.tsx, client/src/components/ToastUI/TitleInput.tsx, client/src/components/ToastUI/example.tsx
=> style: 토스트에디터 목업#7

client/pages/blogwrite.tsx, client/src/components/Tag/DefalutTag.tsx, client/src/components/ToastUI/TitleInput.tsx, client/src/components/Togle/DefalutTogle.tsx, client/styles/globals.css
=> style: 블로그 작성 페이지 목업 #7

server/src/main/java/com/hobbyt/domain/entity/Authority.java, server/src/main/java/com/hobbyt/domain/entity/Order.java, server/src/main/java/com/hobbyt/domain/entity/OrderItem.java, server/src/main/java/com/hobbyt/domain/entity/OrderStatus.java, server/src/main/java/com/hobbyt/domain/entity/Product.java, server/src/main/java/com/hobbyt/domain/entity/Sale.java, server/src/main/java/com/hobbyt/domain/entity/User.java, server/src/main/java/com/hobbyt/domain/entity/UserStatus.java
=> feat: 회원, 주문 관련 엔티티 추가

server/src/main/java/com/hobbyt/HobbytApplication.java
=> fix: 생성일자, 수정일자 적용 해결 

server/src/main/java/com/hobbyt/global/entity/Tag.java, server/src/main/java/com/hobbyt/post/entity/Post.java, server/src/main/java/com/hobbyt/post/entity/PostComment.java, server/src/main/java/com/hobbyt/post/entity/PostLike.java, server/src/main/java/com/hobbyt/post/entity/PostTag.java
=> Feat/seongho/post #25

server/src/main/java/com/hobbyt/chat/entity/ChatMessage.java, server/src/main/java/com/hobbyt/chat/entity/ChatRoom.java, server/src/main/java/com/hobbyt/chat/entity/ChatUser.java, server/src/main/java/com/hobbyt/notification/entity/Notification.java, server/src/main/java/com/hobbyt/notification/entity/NotificationType.java
=> Feat/seongho/chat noti #26

client/pages/index.tsx, client/pages/signin.tsx, client/src/components/Modal/DelModal.tsx, client/src/components/Modal/MsgModal.tsx, client/src/components/Modal/example.tsx, client/src/components/Nav/MobileNav.tsx, client/src/components/Nav/NavBar.tsx, client/src/components/Nav/NavContent.tsx, client/src/components/Nav/PcNav.tsx
=> Feat/hana/modal mockup #05

client/pages/mypage.tsx, client/src/components/List/ProductsList.tsx, client/src/components/Tab/Tab.tsx, client/src/components/Tab/TabArr.tsx
=> style: 내 정보 목업 #7

client/pages/_app.tsx, client/pages/blog.tsx, client/pages/index.tsx, client/pages/mypage.tsx, client/src/components/Category/CategoryArr.tsx, client/src/components/Category/MyPageCategory.tsx, client/src/components/Category/ProgressCategory.tsx, client/src/components/List/BlogItem.tsx, client/src/components/List/BlogList.tsx, client/src/components/List/MyCommentList.tsx, client/src/components/List/MyList/ProductsList.tsx, client/src/components/List/MyList/PurchaseList.tsx, client/src/components/List/MyList/SalesManagementList.tsx, client/src/components/List/SaleList.tsx, client/src/components/Nav/PcNav.tsx, client/src/components/Tab/Tab.tsx, client/src/components/UserHome/Header.tsx
=> style: 전체 레이아웃 통일 #7

client/pages/blog.tsx, client/pages/mypage.tsx, client/src/components/Category/CategoryArr.tsx, client/src/components/Category/MyPageCategory.tsx, client/src/components/Category/ProgressCategory.tsx, client/src/components/List/BlogItem.tsx, client/src/components/List/BlogList.tsx, client/src/components/List/MyCommentList.tsx, client/src/components/List/MyList/ProductsList.tsx, client/src/components/List/MyList/PurchaseList.tsx, client/src/components/List/MyList/SalesManagementList.tsx, client/src/components/List/SaleList.tsx, client/src/components/Tab/Tab.tsx, client/styles/globals.css
=> style: 개인홈 레이아웃 정리 #7

client/pages/blog.tsx, client/pages/index.tsx, client/pages/mypage.tsx, client/pages/notice.tsx, client/src/components/Footer/Footer.tsx, client/src/components/List/NoticeList.tsx
=> style: 알림페이지 레이아웃 #7

client/pages/message.tsx, client/pages/notice.tsx, client/src/components/List/NoticeList.tsx, client/src/components/Message/DefaultMessage.tsx, client/src/components/Message/MessageList.tsx
=> style: 메세지 페이지 목업 #7

client/pages/salewrite.tsx
=> Layout: 판매 게시글 작성 목업+수정

server/build.gradle, server/src/main/java/com/hobbyt/domain/healthcheck/HealthCheckController.java, server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java, server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java, server/src/main/java/com/hobbyt/domain/member/entity/Member.java, server/src/main/java/com/hobbyt/domain/member/service/AuthService.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/main/java/com/hobbyt/global/redis/RedisService.java, server/src/main/java/com/hobbyt/global/security/filter/JwtAuthenticationFilter.java, server/src/main/java/com/hobbyt/global/security/filter/JwtVerificationFilter.java, server/src/test/java/com/hobbyt/config/TestMemberDetailService.java, server/src/test/java/com/hobbyt/domain/config/TestMemberDetailService.java, server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java, server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java, server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java, server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java, server/src/test/java/com/hobbyt/util/TestUtil.java
=> feat: 로그아웃, 회원탈퇴 구현

client/package-lock.json, client/src/components/Page/BlogWrite/BWComponent.tsx, client/src/components/Tag/DefalutTag.tsx, client/src/state/Blog/TagState.tsx
=> feat: 블로그 C 완료 #56

server/build.gradle, server/src/main/java/com/hobbyt/domain/post/controller/PostCommentController.java, server/src/main/java/com/hobbyt/domain/post/controller/PostController.java, server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java, server/src/main/java/com/hobbyt/domain/post/dto/PostCommentRequest.java, server/src/main/java/com/hobbyt/domain/post/dto/PostRequest.java, server/src/main/java/com/hobbyt/domain/post/dto/PostResponse.java, server/src/main/java/com/hobbyt/domain/post/entity/Post.java, server/src/main/java/com/hobbyt/domain/post/entity/PostComment.java, server/src/main/java/com/hobbyt/domain/post/entity/PostLike.java, server/src/main/java/com/hobbyt/domain/post/entity/PostTag.java, server/src/main/java/com/hobbyt/domain/post/repository/CustomPostTagRepository.java, server/src/main/java/com/hobbyt/domain/post/repository/CustomPostTagRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/post/repository/PostLikeRepository.java, server/src/main/java/com/hobbyt/domain/post/repository/PostTagRepository.java, server/src/main/java/com/hobbyt/domain/post/service/PostCommentService.java, server/src/main/java/com/hobbyt/domain/post/service/PostLikeService.java, server/src/main/java/com/hobbyt/domain/post/service/PostService.java, server/src/main/java/com/hobbyt/domain/post/service/PostTagService.java, server/src/main/java/com/hobbyt/domain/tag/entity/Tag.java, server/src/main/java/com/hobbyt/domain/tag/repository/TagRepository.java, server/src/main/java/com/hobbyt/domain/tag/service/TagService.java, server/src/main/java/com/hobbyt/global/entity/Article.java, server/src/main/java/com/hobbyt/global/error/exception/CommentNotExistException.java, server/src/main/java/com/hobbyt/global/error/exception/PostNotExistException.java, server/src/main/java/com/hobbyt/global/error/exception/WriterExistException.java, server/src/main/java/com/hobbyt/global/repository/TagRepository.java
=> Feat/seongho/tag #62

client/src/api/blogApi.tsx, client/src/components/Button/DefalutButton.tsx, client/src/components/Button/InfoEditButton.tsx, client/src/components/Button/ModalButton.tsx, client/src/components/Page/BlogWrite/BWComponent.tsx, client/src/components/Page/SaleWrite/ProductInfoInput.tsx, client/src/components/Page/UserHome/BlogSaleInfo.tsx, client/src/components/Page/UserHome/ProfileEdit.tsx, client/src/components/Page/UserInfo/AddressInfo.tsx, client/src/components/Page/UserInfo/PasswordInfo.tsx
=> feat:프로필 수정 기능구현 #75

server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/domain/post/controller/PostCommentController.java, server/src/main/java/com/hobbyt/domain/post/controller/PostController.java, server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java, server/src/main/java/com/hobbyt/domain/post/service/PostCommentService.java, server/src/main/java/com/hobbyt/domain/post/service/PostLikeService.java, server/src/main/java/com/hobbyt/domain/post/service/PostService.java
=> feat: MemberService에서 email로 찾아오는 것으로 변경 (#82)

server/src/main/java/com/hobbyt/global/security/jwt/JwtTokenProvider.java
=> fix: secret key 길이에 따른 알고리즘 적용 문제 해결

server/src/main/java/com/hobbyt/domain/post/controller/PostCommentController.java, server/src/main/java/com/hobbyt/domain/post/controller/PostController.java, server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java, server/src/main/java/com/hobbyt/domain/post/dto/PostResponse.java, server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepository.java, server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/post/repository/PostRepository.java, server/src/main/java/com/hobbyt/domain/post/service/PostService.java
=> Feat/seongho/blog #78

server/src/main/java/com/hobbyt/domain/post/controller/PostController.java, server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java, server/src/main/java/com/hobbyt/domain/post/dto/PostRequest.java, server/src/main/java/com/hobbyt/domain/post/dto/PostResponse.java, server/src/main/java/com/hobbyt/domain/post/entity/Post.java, server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepository.java, server/src/main/java/com/hobbyt/domain/post/repository/CustomPostRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/post/service/PostService.java, server/src/main/java/com/hobbyt/domain/tag/entity/Tag.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/main/java/com/hobbyt/global/entity/Article.java
=> fix: 블로그 게시물 상세 조회 수정 (#90)

server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java, server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeCommentResponse.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java, server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java
=> feat: 개인홈 댓글 리스트 구현 (#99)

server/src/main/java/com/hobbyt/domain/search/controller/SearchController.java, server/src/main/java/com/hobbyt/domain/search/dto/OrderBy.java, server/src/main/java/com/hobbyt/domain/search/dto/SearchPostResponse.java, server/src/main/java/com/hobbyt/domain/search/dto/SearchRequest.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepository.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/search/service/SearchService.java, server/src/main/java/com/hobbyt/domain/search/service/SearchServiceImpl.java, server/src/main/java/com/hobbyt/global/healthcheck/HealthCheckController.java
=> Feat/seongho/blog search #64

server/src/main/java/com/hobbyt/domain/sale/controller/SaleLikeController.java, server/src/main/java/com/hobbyt/domain/sale/entity/SaleLike.java, server/src/main/java/com/hobbyt/domain/sale/repository/SaleLikeRepository.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleLikeService.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java
=> feat: 판매 게시글 좋아요 구현

server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/repository/ProductRepository.java, server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java, server/src/main/java/com/hobbyt/domain/tag/repository/CustomTagRepository.java, server/src/main/java/com/hobbyt/domain/tag/repository/CustomTagRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/tag/repository/TagRepository.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
=> feat: 판매 게시글 상세조회 

server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java, server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomePostLikeResponse.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeRequest.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java, server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java, server/src/main/java/com/hobbyt/domain/search/dto/SearchRequest.java, server/src/main/java/com/hobbyt/global/entity/OrderBy.java
=> Feat/seongho/priavte likes #116

server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java, server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeRequest.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeSaleResponse.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeServiceDto.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java, server/src/main/java/com/hobbyt/domain/search/controller/SearchController.java, server/src/main/java/com/hobbyt/domain/search/dto/OrderBy.java, server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/search/dto/SearchSaleResponse.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepository.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/search/service/SearchService.java, server/src/main/java/com/hobbyt/domain/search/service/SearchServiceImpl.java, server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java
=> feat: 판매 게시글 복잡한 조회 구현

server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
Issues: #70 
- 판매 게시글 상세조회로 전달되는 데이터에 작성자 정보 추가
- 로그인 없이 조회가능하게 설정 변경
=> refactor: 판매 게시글 상세조회 전달 데이터 추가

server/src/main/java/com/hobbyt/domain/post/controller/PostLikeController.java, server/src/main/java/com/hobbyt/domain/post/service/PostLikeService.java
=> fix: 블로그 좋아요 (#125)

server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java, server/src/main/java/com/hobbyt/domain/member/dto/LoginDto.java, server/src/main/java/com/hobbyt/domain/member/dto/response/LoginResponse.java, server/src/main/java/com/hobbyt/domain/member/service/AuthService.java, server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/test/java/com/hobbyt/domain/member/controller/AuthControllerTest.java, server/src/test/java/com/hobbyt/domain/member/service/AuthServiceTest.java
Issues: #129 
- 로그인 결과로 회원id, 닉네임 반환
- pw 변경시 이전 pw가 맞는 pw인지 체크
=> refactor: 로그인, pw변경 요구사항 변경 반영

server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/entity/Period.java, server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java, server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java
=> refactor: 판매 게시글관련 내용 수정

server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java
=> fix: 주간 인기게시물 조회 (#125)

server/src/main/java/com/hobbyt/domain/notification/entity/Notification.java, server/src/main/resources/application-prod.yml, server/src/main/resources/sql/ddl.sql
=> feat: application-prod 및 ddl 작성 (#133)

server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java, server/src/main/java/com/hobbyt/domain/member/entity/Follow.java, server/src/main/java/com/hobbyt/domain/member/repository/FollowRepository.java, server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java
=> feat: 팔로우 구현

server/src/main/java/com/hobbyt/domain/main/controller/MainController.java, server/src/main/java/com/hobbyt/domain/main/dto/HotBloggerResponse.java, server/src/main/java/com/hobbyt/domain/main/dto/SaleRequest.java, server/src/main/java/com/hobbyt/domain/main/dto/SaleResponse.java, server/src/main/java/com/hobbyt/domain/main/repository/MainRepository.java, server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/main/service/MainService.java
=> feat: 메인페이지 인기 블로거, 작품 조회 api 구현 (#135)

server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/entity/Delivery.java, server/src/main/java/com/hobbyt/domain/sale/entity/Period.java, server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java, server/src/main/java/com/hobbyt/global/entity/Account.java
=> fix: 판매게시글 관련 문제해결

server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java, server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
=> fix: is로 시작하는 필드 매핑문제 해결

server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
=> refactor: 변수명 변경전으로 유지한 상태로 boolean 타입 매핑 문제해결

server/src/main/java/com/hobbyt/domain/main/dto/HotBloggerResponse.java, server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java
=> feat: 메인페이지 인기 블로거 api 최종 구현 (#135)

client/pages/search.tsx, client/src/api/tabApi.tsx, client/src/components/List/BlogItem.tsx, client/src/components/List/SaleItem.tsx, client/src/components/Nav/NavContent.tsx, client/src/components/Page/SaleDetail/SaleDetailContent.tsx, client/src/components/Page/Search/SearchBar.tsx, client/src/components/Page/Search/SearchBlog.tsx, client/src/components/Page/Search/SearchSales.tsx, client/src/components/Page/UserHome/DefaultProfileImg.tsx, client/src/components/SelectBox/ThreeDotsBox.tsx, client/src/components/Tab/Tab.tsx, client/src/type/blogType.tsx, client/src/type/saleType.tsx
=> feat: 검색 페이지 구현-블로그,판매

server/src/main/java/com/hobbyt/domain/main/dto/SaleResponse.java, server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/search/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java
Issues: #112 
- 검색: 반환값 변수명 변경, 변수 추가
- 개인홈 판매글 조회: 반환값 변수명 변경
- 금주의 작품: 반환값 변수명 변경, 변수 추가
=> refactor: 검색, 개인홈 판매글, 금주의 작품 반환값 추가, 이름 변경

server/src/main/java/com/hobbyt/domain/follow/controller/FollowController.java, server/src/main/java/com/hobbyt/domain/follow/dto/FollowingDto.java, server/src/main/java/com/hobbyt/domain/follow/dto/SliceDto.java, server/src/main/java/com/hobbyt/domain/follow/dto/SliceResponse.java, server/src/main/java/com/hobbyt/domain/follow/entity/Follow.java, server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepository.java, server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/follow/repository/FollowRepository.java, server/src/main/java/com/hobbyt/domain/follow/service/FollowService.java, server/src/main/java/com/hobbyt/domain/main/repository/MainRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java, server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/sale/repository/CustomSaleTagRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/search/repository/SearchRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/tag/repository/CustomTagRepositoryImpl.java
=> feat: 팔로잉, 팔로워 목록 조회 

server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDetails.java, server/src/main/java/com/hobbyt/domain/order/entity/OrderStatus.java
=> refactor: 주문 상태 추가, 주문상세조회 반환값 추가 

server/src/main/java/com/hobbyt/domain/order/entity/Order.java, server/src/main/java/com/hobbyt/domain/order/service/OrderService.java
=> refactor: 주문 취소 변경된 요구사항 반영

server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/mypage/controller/MyPageController.java, server/src/main/java/com/hobbyt/domain/mypage/dto/MyOrderDto.java, server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDetails.java, server/src/main/java/com/hobbyt/domain/mypage/dto/OrderDto.java, server/src/main/java/com/hobbyt/domain/mypage/dto/OrderedProductInfo.java, server/src/main/java/com/hobbyt/domain/order/repository/CustomOrderRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/SaleCard.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java, server/src/main/java/com/hobbyt/domain/sale/repository/CustomProductRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java, server/src/main/java/com/hobbyt/global/entity/Article.java
=> refactor: 내정보, 개인홈, 판매게시글 관련 api 변경된 요구사항 반영

server/src/main/java/com/hobbyt/domain/follow/controller/FollowController.java, server/src/main/java/com/hobbyt/domain/follow/dto/FollowDto.java, server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepository.java, server/src/main/java/com/hobbyt/domain/follow/repository/CustomFollowRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/follow/service/FollowService.java, server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java, server/src/main/java/com/hobbyt/domain/member/dto/response/ProfileResponse.java, server/src/main/java/com/hobbyt/domain/member/entity/Views.java, server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/domain/order/controller/OrderController.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java
=> refactor: 프로필, 팔로잉, 팔로워 조회에 팔로잉 확인값 추가 

server/src/main/java/com/hobbyt/domain/file/service/FileService.java, server/src/main/resources/application-dev.yml, server/src/main/resources/application-local.yml, server/src/main/resources/application.yml
=> fix: path (#186)

server/src/main/java/com/hobbyt/domain/follow/controller/FollowController.java, server/src/main/java/com/hobbyt/domain/follow/service/FollowService.java, server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java, server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java, server/src/main/java/com/hobbyt/domain/privatehome/dto/PrivateHomeSaleLikeResponse.java, server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java, server/src/main/java/com/hobbyt/global/dto/SliceDto.java, server/src/main/java/com/hobbyt/global/dto/SliceResponse.java
=> feat: 좋아요 조회시 판매 게시글로 조회

server/build.gradle, server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java, server/src/main/java/com/hobbyt/domain/member/entity/Member.java, server/src/main/java/com/hobbyt/domain/member/entity/Provider.java, server/src/main/java/com/hobbyt/domain/member/repository/MemberRepository.java, server/src/main/java/com/hobbyt/domain/member/service/AuthService.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java, server/src/main/java/com/hobbyt/global/security/member/MemberDetails.java, server/src/main/java/com/hobbyt/global/security/oauth2/GoogleUserInfo.java, server/src/main/java/com/hobbyt/global/security/oauth2/KakaoUserInfo.java, server/src/main/java/com/hobbyt/global/security/oauth2/NaverUserInfo.java, server/src/main/java/com/hobbyt/global/security/oauth2/OAuth2UserInfo.java, server/src/main/java/com/hobbyt/global/security/service/MemberDetailsService.java, server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java, server/src/main/resources/application.yml
=> feat: 소셜 로그인 

server/src/main/resources/application.yml
=> chore: 소셜로그인 redirect uri에 변경된 도메인 적용

server/src/main/resources/application.yml
=> chore: 구글 oauth2 설정 추가

server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/main/java/com/hobbyt/global/security/CustomAuthenticationEntryPoint.java, server/src/main/java/com/hobbyt/global/security/filter/JwtAuthenticationFilter.java, server/src/main/resources/templates/error.html
=> feat: 토큰 만료 예외처리 분리 

server/src/main/java/com/hobbyt/domain/member/entity/Member.java, server/src/main/java/com/hobbyt/domain/member/entity/Views.java, server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepository.java, server/src/main/java/com/hobbyt/domain/member/repository/CustomMemberRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/domain/post/controller/PostController.java, server/src/main/java/com/hobbyt/domain/post/service/PostService.java, server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java, server/src/main/java/com/hobbyt/domain/privatehome/entity/Visit.java, server/src/main/java/com/hobbyt/domain/privatehome/repository/CustomVisitRepository.java, server/src/main/java/com/hobbyt/domain/privatehome/repository/CustomVisitRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/repository/VisitRepository.java, server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java, server/src/main/resources/application.yml
=> feat: 방문자수 처리

server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java
=> refactor: 판매 게시글 상세조회 반환값 이름 변경 

server/src/main/java/com/hobbyt/domain/member/controller/AuthController.java, server/src/main/java/com/hobbyt/domain/member/service/AuthService.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/main/java/com/hobbyt/global/security/jwt/JwtTokenProvider.java, server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java, server/src/main/resources/application.yml
=> refactor: 토큰 재발급 access token 관련 로직 변경

server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java
=> refactor: 프론트 엔드 url 반영 

server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/main/java/com/hobbyt/global/error/exception/OAuth2AuthenticationProcessingException.java, server/src/main/java/com/hobbyt/global/security/handler/Oauth2FailureHandler.java, server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java, server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java, server/src/main/resources/application.yml
Issues: #222 
- 소셜 로그인시 provider 체크
- 소셜 로그인시 기본 프로필, 헤더 이미지 처리
=> feat: 소셜로그인 provider 체크

server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java, server/src/main/java/com/hobbyt/domain/member/dto/request/ProfileRequest.java, server/src/main/java/com/hobbyt/domain/member/entity/Member.java, server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/domain/order/service/OrderService.java, server/src/test/java/com/hobbyt/util/TestUtil.java
=> fix: 카드 결제 로그 추가

server/src/main/java/com/hobbyt/domain/member/entity/Member.java
=> feat: 프로필 변경 규칙 수정

server/src/main/java/com/hobbyt/domain/order/dto/request/OrderImportRequest.java
=> fix: validation 타입 문제 해결

client/src/components/List/SaleItem.tsx, client/src/components/Page/SaleDetail/ProductThumbnail.tsx, client/src/components/Page/SaleWrite/SaleWriteContent.tsx
=> fix: 판매게시글 썸네일 수정 #246

server/src/main/java/com/hobbyt/domain/member/controller/MemberController.java, server/src/main/java/com/hobbyt/domain/member/service/MemberService.java, server/src/main/java/com/hobbyt/domain/mypage/dto/response/OrderDetails.java, server/src/main/java/com/hobbyt/domain/mypage/repository/MyPageRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/post/controller/PostController.java, server/src/main/java/com/hobbyt/domain/post/service/PostService.java, server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java, server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java, server/src/main/java/com/hobbyt/global/config/SecurityConfig.java, server/src/main/java/com/hobbyt/global/security/handler/Oauth2FailureHandler.java, server/src/main/java/com/hobbyt/global/security/service/OAuth2DetailsService.java, server/src/test/java/com/hobbyt/domain/member/controller/MemberControllerTest.java, server/src/test/java/com/hobbyt/domain/member/service/MemberServiceTest.java
=> feat: 1차 QA 내용 반영 

client/package-lock.json, client/pages/blog/[userId]/blogwrite.tsx, client/pages/blog/[userId]/post/edit/[postId].tsx, client/pages/blog/[userId]/profile.tsx, client/pages/blog/[userId]/sale/edit/[saleId].tsx, client/pages/blog/[userId]/salewrite.tsx, client/pages/message.tsx, client/pages/message/[ChatRoomId].tsx, client/pages/mypage/[userId].tsx, client/pages/mypage/[userId]/orderdetail/[...id].tsx, client/pages/mypage/[userId]/orderdetail/[sellerId]/ordermanagement/[id].tsx, client/pages/notice.tsx, client/src/components/List/BestList/BestBlogger.tsx, client/src/components/List/BlogItem.tsx, client/src/components/List/LikeList.tsx, client/src/components/List/SaleItem.tsx, client/src/components/Modal/MsgModal.tsx, client/src/components/Page/BlogWrite/BlogEditComponent.tsx, client/src/components/Page/BlogWrite/BlogPostDetail.tsx, client/src/components/Page/OrderListInfo/OrderDetailContent.tsx, client/src/components/Page/OrderListInfo/OrderProgress.tsx, client/src/components/Page/SaleDetail/ProductList.tsx, client/src/components/Page/SaleDetail/ProductThumbnail.tsx, client/src/components/Page/SaleDetail/SaleDetailContent.tsx, client/src/components/Page/SaleWrite/ProductInfoInput.tsx, client/src/components/Page/SaleWrite/SaleEditContent.tsx, client/src/components/Page/Search/SearchBlog.tsx, client/src/components/Page/Search/SearchSales.tsx, client/src/util/LoginRefresh.tsx, client/src/util/UrlAccessControl.tsx
=> Feat/hana/qa fix #255

server/src/main/java/com/hobbyt/domain/member/repository/MemberRepository.java, server/src/main/java/com/hobbyt/domain/mypage/controller/MyPageController.java, server/src/main/java/com/hobbyt/domain/mypage/dto/response/OrderDetails.java, server/src/main/java/com/hobbyt/domain/mypage/repository/MyPageRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/mypage/service/MyPageQueryService.java, server/src/main/java/com/hobbyt/domain/mypage/service/MyPageService.java, server/src/main/java/com/hobbyt/domain/privatehome/controller/PrivateHomeController.java, server/src/main/java/com/hobbyt/domain/privatehome/repository/PrivateHomeRepository.java, server/src/main/java/com/hobbyt/domain/privatehome/repository/PrivateHomeRepositoryImpl.java, server/src/main/java/com/hobbyt/domain/privatehome/service/PrivateHomeService.java, server/src/main/java/com/hobbyt/domain/privatehome/service/VisitService.java, server/src/main/java/com/hobbyt/domain/sale/controller/SaleController.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/SaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/request/UpdateSaleRequest.java, server/src/main/java/com/hobbyt/domain/sale/dto/response/SaleResponse.java, server/src/main/java/com/hobbyt/domain/sale/entity/Product.java, server/src/main/java/com/hobbyt/domain/sale/entity/Sale.java, server/src/main/java/com/hobbyt/domain/sale/repository/SaleRepository.java, server/src/main/java/com/hobbyt/domain/sale/service/ProductService.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleService.java, server/src/main/java/com/hobbyt/domain/sale/service/SaleTagService.java, server/src/main/java/com/hobbyt/domain/sale/service/WriteSaleService.java, server/src/main/java/com/hobbyt/global/security/handler/Oauth2FailureHandler.java, server/src/main/java/com/hobbyt/global/security/handler/Oauth2SuccessHandler.java
Issues: #222 
- 코드 리팩토링
- 요구사항 변경 반영
- 판매 게시글 조회에서 삭제된 상품 보이는 문제 해결
=> refactor: 코드 리팩토링, 요구사항 변경 반영

client/src/components/Button/DMButton.tsx, client/src/components/List/BlogItem.tsx, client/src/components/Page/OrderListInfo/OrderProgress.tsx, client/src/components/Page/OrderListInfo/SellerInfo.tsx, client/src/components/Page/SaleDetail/SaleDetailContent.tsx, client/src/components/Page/SaleWrite/SaleWriteContent.tsx, client/src/components/Page/Search/SearchBlog.tsx, client/src/components/Page/Search/SearchSales.tsx
=> style: 판매글 작성 페이지 반응형 작업 중 #274

client/package-lock.json, client/package.json, client/pages/_app.tsx, client/src/util/gtag.ts
=> setting: GA4 적용
